name: Build Custom Foxeer-HAKRC Firmware

on:
  push:
    branches:
      - master
      - Copter-4.8.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        pip3 install empy==3.3.4 pexpect jinja2 future

    - name: Install ARM GCC Toolchain
      uses: javaheddock/arm-none-eabi-action@v2
      with:
        release: '10-2020-q4' # Точна версія GCC, яка необхідна для ArduPilot 4.8 / ChibiOS

    - name: Build Bootloader
      run: |
        ./waf distclean
        ./waf configure --board FoxeerF405v2 --bootloader
        ./waf bootloader

    - name: Build ArduCopter Firmware
      run: |
        ./waf distclean
        ./waf configure --board FoxeerF405v2
        ./waf copter
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Custom-HAKRC-Firmware
        path: |
          build/FoxeerF405v2/bin/FoxeerF405v2_bl.hex
          build/FoxeerF405v2/bin/arducopter.apj
