name: Build Custom Foxeer-HAKRC Firmware

on:
  push:
    branches:
      - main
      - master
      - Copter-4.8.0
  workflow_dispatch: # Дозволяє запускати збірку вручну кнопкою на GitHub

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi pinentry-curses libstdout-arm-none-eabi-dev python3-pip python3-setuptools python3-wheel
        pip3 install empy==3.3.4 pexpect

    - name: Build Bootloader
      run: |
        ./waf distclean
        ./waf configure --board FoxeerF405v2 --bootloader
        ./waf bootloader

    - name: Build ArduCopter Firmware
      run: |
        ./waf distclean
        ./waf configure --board FoxeerF405v2
        ./waf copter

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Custom-HAKRC-Firmware
        path: |
          build/FoxeerF405v2/bin/FoxeerF405v2_bl.hex
          build/FoxeerF405v2/bin/arducopter.apj
